# Generated by Django 4.0.4 on 2022-05-03 11:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('project_done', models.PositiveIntegerField(default=0, verbose_name='Project Done')),
                ('happy_clients', models.PositiveIntegerField(default=0, verbose_name='Happy Clients')),
                ('employee', models.PositiveIntegerField(default=0, verbose_name='Employee Count')),
            ],
        ),
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=12, verbose_name='Mobile Number')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=12, verbose_name='Mobile Number')),
                ('feedback', models.TextField(verbose_name='Feedback')),
                ('rate', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='Rating')),
            ],
        ),
        migrations.CreateModel(
            name='service_category',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Category name')),
                ('descript', models.TextField(verbose_name='Category Description')),
                ('image', models.ImageField(upload_to='Media', verbose_name='Category Image')),
            ],
        ),
        migrations.CreateModel(
            name='testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50, verbose_name='Client name')),
                ('client_image', models.ImageField(upload_to='Media', verbose_name='Client Image')),
                ('feedback', models.TextField(verbose_name='Feedback')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='Rating by client')),
            ],
        ),
        migrations.CreateModel(
            name='service_sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat_name', models.CharField(max_length=30, verbose_name='Sub Category Name')),
                ('sub_descript', models.TextField(verbose_name='Sub Category Description')),
                ('sub_img', models.ImageField(upload_to='Media', verbose_name='Sub Category Image')),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintnf.service_category', verbose_name='Category name')),
            ],
        ),
    ]
