# Generated by Django 4.0.4 on 2022-05-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintnf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_category',
            name='image',
            field=models.ImageField(null=True, upload_to='Media', verbose_name='Category Image'),
        ),
        migrations.AddField(
            model_name='service_sub_category',
            name='sub_img',
            field=models.ImageField(null=True, upload_to='Media', verbose_name='Sub Category Image'),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='client_image',
            field=models.ImageField(null=True, upload_to='Media', verbose_name='Client Image'),
        ),
    ]
