# Generated by Django 4.0.4 on 2022-05-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintnf', '0002_service_category_image_service_sub_category_sub_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='address',
            field=models.TextField(null=True, verbose_name='Address'),
        ),
    ]
