# Generated by Django 4.0.4 on 2022-05-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintnf', '0003_contact_us_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(null=True, upload_to='Media', verbose_name='Profile picture')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('profession', models.CharField(max_length=30, verbose_name='Profession')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
