# Generated by Django 4.0.4 on 2022-05-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintnf', '0004_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Client Name')),
                ('image', models.ImageField(upload_to='Media', verbose_name='Client Image')),
                ('description', models.TextField(verbose_name='Description')),
                ('project', models.CharField(max_length=100, verbose_name='Project name')),
            ],
        ),
    ]
